---
kind: Pipeline
apiVersion: v1alpha1
metadata:
  name: pingpong
  namespace: acaleph
spec:
  selector:
    matchLabels:
      app: pingpong
      type: api
  template:
    metadata:
      name: pingpong
      labels:
        app: service
        type: api
    notif:
      - type: slack
        metadata:
          url: slackurl 
          channel: slackchannel
          user: slackuser
    secrets:
      - acaleph-notifier
      - quayregistrycreds
    stages:
      - name: Build and Unit Test
        type: command
        params:
          image: golang:1.6
          command:
            - make
            - build
        artifacts:
          - build/bin/**
      - name: Package App
        type: command
        params:
          image: docker:1.8.3
          command:
            - ./package-app.sh
            - /kontinuous/src/artifacts/pingpong
      - name: Integration Test
        type: command
        params: 
           image: debian:jessie
           command:
              - ./integration-test.sh
              - http://pingpong-test:8080
           dependencies:
              - integration-test.yaml
      - name: Deploy App
        type: command
        params:
          deploy: true
          deploy_file: manifest.yaml
      # This should run the application together in the Job
      # and we run integration tests
      # - name: Integration Test
      #   with_containers:
      #     - name: pingpong-app
      #       params:
      #         image: 
      # # This should deploy the finish product. :) 
      # - name: Deploy App
      #   type: deploy
      #   params:
      #     service:
      #       ports:
      #     deployment:
      #       containers:
      #         - 
