---
kind: Service
apiVersion: v1
metadata:
  name: pingpong-test
  namespace: acaleph
  labels:
    app: pingpong
    type: api
    env: testing
spec:
  selector:
    app: pingpong
    type: api
    env: testing
  ports:
    - name: api
      port: 8080
      targetPort: 8080

---
kind: ReplicationController
apiVersion: v1
metadata:
  name: pingpong-test
  namespace: acaleph
  labels:
    app: pingpong
    type: api
    env: testing
spec:
  replicas: 1
  template:
    metadata:
      name: pingpong-test
      labels:
        app: pingpong
        type: api
        env: testing
    spec:
      containers:
        - name: pingpong-test
          image: quay.io/acaleph/pingpong:latest
          imagePullPolicy: Always
          ports:
            - name: api
              containerPort: 8080
