---
kind: Service
apiVersion: v1
metadata:
  name: pingpongtest
  namespace: acaleph
spec:
  selector:
    app: pingpong-test
    type: ci-cd
  ports:
    - name: api
      port: 8080
      targetPort: 8080
---
kind: Pod
apiVersion: v1
metadata:
  name: pingpongtest
  namespace: acaleph
  labels:
    app: pingpong-test
    type: ci-cd    
spec:
  containers:
    - name: pingpongtest
      image: quay.io/acaleph/pingpong:latest
      imagePullPolicy: Always
      ports:
        - name: api
          containerPort: 8080
          protocol: TCP